.TH "DestinationListHandler::TransportAddress" 3 "21 Sep 2010" "ccRTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DestinationListHandler::TransportAddress \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <oqueue.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransportAddress\fP (InetAddress na, tpport_t dtp, tpport_t ctp)"
.br
.ti -1c
.RI "const InetAddress & \fBgetNetworkAddress\fP () const "
.br
.ti -1c
.RI "tpport_t \fBgetDataTransportPort\fP () const "
.br
.ti -1c
.RI "tpport_t \fBgetControlTransportPort\fP () const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "InetAddress \fBnetworkAddress\fP"
.br
.ti -1c
.RI "tpport_t \fBdataTransportPort\fP"
.br
.ti -1c
.RI "tpport_t \fBcontrolTransportPort\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DestinationListHandler::TransportAddress::TransportAddress (InetAddress na, tpport_t dtp, tpport_t ctp)\fC [inline]\fP"
.SH "Member Function Documentation"
.PP 
.SS "tpport_t DestinationListHandler::TransportAddress::getControlTransportPort () const\fC [inline]\fP"
.SS "tpport_t DestinationListHandler::TransportAddress::getDataTransportPort () const\fC [inline]\fP"
.SS "const InetAddress& DestinationListHandler::TransportAddress::getNetworkAddress () const\fC [inline]\fP"
.SH "Member Data Documentation"
.PP 
.SS "tpport_t \fBDestinationListHandler::TransportAddress::controlTransportPort\fP"
.SS "tpport_t \fBDestinationListHandler::TransportAddress::dataTransportPort\fP"
.SS "InetAddress \fBDestinationListHandler::TransportAddress::networkAddress\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for ccRTP from the source code.
