.TH "ext.h" 3 "21 Sep 2010" "ccRTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ext.h \- 
.PP
ccRTP Stack extensions.  

.SH SYNOPSIS
.br
.PP
\fC#include <cc++/socket.h>\fP
.br
\fC#include <ccrtp/ioqueue.h>\fP
.br
\fC#include <ccrtp/channel.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRTPDuplex\fP"
.br
.RI "\fIA peer associated RTP socket pair for physically connected peer hosts. \fP"
.in -1c
.SH "Detailed Description"
.PP 
ccRTP Stack extensions. 


.SH "Author"
.PP 
Generated automatically by Doxygen for ccRTP from the source code.
