.TH "Generic RTP input/output queues." 3 "21 Sep 2010" "ccRTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Generic RTP input/output queues. \- 
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRTPDataQueue\fP"
.br
.RI "\fIA packet queue handler for building different kinds of RTP protocol systems. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ccRTP from the source code.
