.TH "Members" 3 "21 Sep 2010" "ccRTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Members \- 
.PP
members and senders accounting  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <iqueue.h>\fP
.PP
Inherited by \fBMembershipBookkeeping\fP\fC [private]\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetMembersCount\fP (uint32 n)"
.br
.ti -1c
.RI "void \fBincreaseMembersCount\fP ()"
.br
.ti -1c
.RI "void \fBdecreaseMembersCount\fP ()"
.br
.ti -1c
.RI "uint32 \fBgetMembersCount\fP () const "
.br
.ti -1c
.RI "void \fBsetSendersCount\fP (uint32 n)"
.br
.ti -1c
.RI "void \fBincreaseSendersCount\fP ()"
.br
.ti -1c
.RI "void \fBdecreaseSendersCount\fP ()"
.br
.ti -1c
.RI "uint32 \fBgetSendersCount\fP () const "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBMembers\fP ()"
.br
.ti -1c
.RI "virtual \fB~Members\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
members and senders accounting 

Records the number of members as well as active senders. For now, it is too simple.
.PP
\fBAuthor:\fP
.RS 4
Federico Montesino Pouzols <fedemp@altern.org> 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "Members::Members ()\fC [inline, protected]\fP"
.SS "virtual Members::~Members ()\fC [inline, protected, virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "void Members::decreaseMembersCount ()\fC [inline]\fP"
.SS "void Members::decreaseSendersCount ()\fC [inline]\fP"
.SS "uint32 Members::getMembersCount () const\fC [inline]\fP"
.SS "uint32 Members::getSendersCount () const\fC [inline]\fP"
.SS "void Members::increaseMembersCount ()\fC [inline]\fP"
.SS "void Members::increaseSendersCount ()\fC [inline]\fP"
.SS "void Members::setMembersCount (uint32 n)\fC [inline]\fP"
.PP
Reimplemented in \fBMembershipBookkeeping\fP.
.SS "void Members::setSendersCount (uint32 n)\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for ccRTP from the source code.
