.TH "PredEquals" 3 "21 Sep 2010" "ccRTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PredEquals \- 
.PP
std equality for \fBSessionListElement\fP objects.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pool.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPredEquals\fP (\fBRTPSessionBase\fP *e)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (\fBSessionListElement\fP *e)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBRTPSessionBase\fP * \fBelem\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
std equality for \fBSessionListElement\fP objects. 

\fBAuthor:\fP
.RS 4
Jorgen Terner 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "PredEquals::PredEquals (\fBRTPSessionBase\fP * e)\fC [inline]\fP"
.SH "Member Function Documentation"
.PP 
.SS "bool PredEquals::operator() (\fBSessionListElement\fP * e)\fC [inline]\fP"
.SH "Member Data Documentation"
.PP 
.SS "\fBRTPSessionBase\fP* \fBPredEquals::elem\fP\fC [protected]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for ccRTP from the source code.
