.TH "queuebase.h" 3 "21 Sep 2010" "ccRTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
queuebase.h \- 
.PP
Base classes for RTP queues.  

.SH SYNOPSIS
.br
.PP
\fC#include <cc++/pointer.h>\fP
.br
\fC#include <ccrtp/rtppkt.h>\fP
.br
\fC#include <ccrtp/sources.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAppDataUnit\fP"
.br
.RI "\fIInterface (envelope) to data received over RTP packets. \fP"
.ti -1c
.RI "class \fBRTPQueueBase\fP"
.br
.RI "\fIA virtual base class for RTP queue hierarchies. \fP"
.ti -1c
.RI "class \fBOutgoingDataQueueBase\fP"
.br
.ti -1c
.RI "class \fBIncomingDataQueueBase\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base classes for RTP queues. 


.SH "Author"
.PP 
Generated automatically by Doxygen for ccRTP from the source code.
