.TH "RTCPCompoundHandler::RecvReport" 3 "21 Sep 2010" "ccRTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTCPCompoundHandler::RecvReport \- 
.PP
raw structure of the source and every receiver report in an SR or RR RTCP packet.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rtcppkt.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32 \fBssrc\fP"
.br
.RI "\fIsource identifier. \fP"
.ti -1c
.RI "\fBRRBlock\fP \fBblocks\fP [1]"
.br
.RI "\fIreceiver report blocks. \fP"
.in -1c
.SH "Detailed Description"
.PP 
raw structure of the source and every receiver report in an SR or RR RTCP packet. 
.SH "Member Data Documentation"
.PP 
.SS "\fBRRBlock\fP \fBRTCPCompoundHandler::RecvReport::blocks\fP[1]"
.PP
receiver report blocks. 
.SS "uint32 \fBRTCPCompoundHandler::RecvReport::ssrc\fP"
.PP
source identifier. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ccRTP from the source code.
