.TH "RTCPCompoundHandler::RRBlock" 3 "21 Sep 2010" "ccRTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTCPCompoundHandler::RRBlock \- 
.PP
Struct for a receiver info block in a SR (sender report) or an RR (receiver report) RTCP packet.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rtcppkt.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32 \fBssrc\fP"
.br
.RI "\fIsource identifier. \fP"
.ti -1c
.RI "\fBReceiverInfo\fP \fBrinfo\fP"
.br
.RI "\fIinfo about the source. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Struct for a receiver info block in a SR (sender report) or an RR (receiver report) RTCP packet. 
.SH "Member Data Documentation"
.PP 
.SS "\fBReceiverInfo\fP \fBRTCPCompoundHandler::RRBlock::rinfo\fP"
.PP
info about the source. 
.SS "uint32 \fBRTCPCompoundHandler::RRBlock::ssrc\fP"
.PP
source identifier. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ccRTP from the source code.
