.TH "RTCP compound packets manipulation." 3 "21 Sep 2010" "ccRTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTCP compound packets manipulation. \- 
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRTCPCompoundHandler\fP"
.br
.RI "\fIlow level structs and RTCP packet parsing and building methods. \fP"
.ti -1c
.RI "class \fBRTCPReceiverInfo\fP"
.br
.RI "\fIReport block information of SR/RR RTCP reports. \fP"
.ti -1c
.RI "class \fBRTCPSenderInfo\fP"
.br
.RI "\fISender block information of SR RTCP reports. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBSDESItemType\fP { \fBSDESItemTypeEND\fP =  0, \fBSDESItemTypeCNAME\fP, \fBSDESItemTypeNAME\fP, \fBSDESItemTypeEMAIL\fP, \fBSDESItemTypePHONE\fP, \fBSDESItemTypeLOC\fP, \fBSDESItemTypeTOOL\fP, \fBSDESItemTypeNOTE\fP, \fBSDESItemTypePRIV\fP, \fBSDESItemTypeH323CADDR\fP, \fBSDESItemTypeLast\fP =  SDESItemTypeH323CADDR }"
.br
.RI "\fISDES items that may be carried in a Source DEScription RTCP packet. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "timeval \fBNTP2Timeval\fP (uint32 msw, uint32 lsw)"
.br
.RI "\fIConvert a NTP timestamp, expressed as two 32-bit long words, into a timeval value. \fP"
.ti -1c
.RI "uint32 \fBtimevalIntervalTo65536\fP (timeval &t)"
.br
.RI "\fIConvert a time interval, expressed as a timeval, into a 32-bit time interval expressed in units of 1/65536 seconds. \fP"
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBSDESItemType\fP"
.PP
SDES items that may be carried in a Source DEScription RTCP packet. CNAME is mandatory in each RTCP compound packet (except when splitted for partial encryption), the others are optional and have different sending frequencies, though with recommended default values. 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fISDESItemTypeEND \fP\fP
END of SDES item list. 
.TP
\fB\fISDESItemTypeCNAME \fP\fP
Canonical end-point identifier. 
.TP
\fB\fISDESItemTypeNAME \fP\fP
Personal NAME of the user. 
.TP
\fB\fISDESItemTypeEMAIL \fP\fP
EMAIL address of the user. 
.TP
\fB\fISDESItemTypePHONE \fP\fP
Phone number of the user. 
.TP
\fB\fISDESItemTypeLOC \fP\fP
Location where the user is. 
.TP
\fB\fISDESItemTypeTOOL \fP\fP
Application or tool. 
.TP
\fB\fISDESItemTypeNOTE \fP\fP
Comment usually reporting state. 
.TP
\fB\fISDESItemTypePRIV \fP\fP
Private extension. 
.TP
\fB\fISDESItemTypeH323CADDR \fP\fP
H323 callable address. 
.TP
\fB\fISDESItemTypeLast \fP\fP
Last defined code. 
.SH "Function Documentation"
.PP 
.SS "timeval NTP2Timeval (uint32 msw, uint32 lsw)"
.PP
Convert a NTP timestamp, expressed as two 32-bit long words, into a timeval value. \fBParameters:\fP
.RS 4
\fImsw\fP Integer part of NTP timestamp. 
.br
\fIlsw\fP Fractional part of NTP timestamp. 
.RE
.PP
\fBReturns:\fP
.RS 4
timeval value corresponding to the given NTP timestamp. 
.RE
.PP

.SS "uint32 timevalIntervalTo65536 (timeval & t)"
.PP
Convert a time interval, expressed as a timeval, into a 32-bit time interval expressed in units of 1/65536 seconds. \fBParameters:\fP
.RS 4
\fIt\fP Timeval interval. 
.RE
.PP
\fBReturns:\fP
.RS 4
32-bit value corresponding to the given timeval interval. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for ccRTP from the source code.
