.TH "RTCPCompoundHandler::RTCPFixedHeader" 3 "21 Sep 2010" "ccRTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTCPCompoundHandler::RTCPFixedHeader \- 
.PP
Fixed RTCP packet header.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rtcppkt.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBversion\fP:2"
.br
.RI "\fI< For big endian boxes \fP"
.ti -1c
.RI "unsigned char \fBpadding\fP:1"
.br
.RI "\fIPadding bit. \fP"
.ti -1c
.RI "unsigned char \fBblock_count\fP:5"
.br
.RI "\fINumber of RR, SR, or SDES chunks. \fP"
.ti -1c
.RI "uint8 \fBtype\fP"
.br
.RI "\fItype of RTCP packet. \fP"
.ti -1c
.RI "uint16 \fBlength\fP"
.br
.RI "\fInumber of 32-bit words in the packet (*minus one*). \fP"
.in -1c
.SH "Detailed Description"
.PP 
Fixed RTCP packet header. 

First 32-bit word in any RTCP packet. 
.SH "Member Data Documentation"
.PP 
.SS "unsigned char \fBRTCPCompoundHandler::RTCPFixedHeader::block_count\fP"
.PP
Number of RR, SR, or SDES chunks. 
.SS "uint16 \fBRTCPCompoundHandler::RTCPFixedHeader::length\fP"
.PP
number of 32-bit words in the packet (*minus one*). 
.SS "unsigned char \fBRTCPCompoundHandler::RTCPFixedHeader::padding\fP"
.PP
Padding bit. 
.SS "uint8 \fBRTCPCompoundHandler::RTCPFixedHeader::type\fP"
.PP
type of RTCP packet. 
.SS "unsigned char \fBRTCPCompoundHandler::RTCPFixedHeader::version\fP"
.PP
< For big endian boxes Version, currently 2. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ccRTP from the source code.
