.TH "RTPPacket::RFC2833Payload" 3 "21 Sep 2010" "ccRTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTPPacket::RFC2833Payload \- 
.PP
a structure defining RFC2833 Telephony events.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rtppkt.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8 \fBevent\fP: 8"
.br
.ti -1c
.RI "bool \fBebit\fP: 1"
.br
.ti -1c
.RI "bool \fBrbit\fP: 1"
.br
.ti -1c
.RI "uint8 \fBvol\fP: 6"
.br
.ti -1c
.RI "uint16 \fBduration\fP: 16"
.br
.in -1c
.SH "Detailed Description"
.PP 
a structure defining RFC2833 Telephony events. 

structure to define RFC2833 telephony events in RTP. You can use this by recasing the pointer returned by \fBgetPayload()\fP. 
.SH "Member Data Documentation"
.PP 
.SS "uint16 \fBRTPPacket::RFC2833Payload::duration\fP"
.SS "bool \fBRTPPacket::RFC2833Payload::ebit\fP"
.SS "uint8 \fBRTPPacket::RFC2833Payload::event\fP"
.SS "bool \fBRTPPacket::RFC2833Payload::rbit\fP"
.SS "uint8 \fBRTPPacket::RFC2833Payload::vol\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for ccRTP from the source code.
