.TH "RTPSessionBaseHandler" 3 "21 Sep 2010" "ccRTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTPSessionBaseHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pool.h>\fP
.PP
Inherited by \fBRTPSessionPool\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmicrotimeout_t\fP \fBgetSchedulingTimeout\fP (\fBRTPSessionBase\fP &s)"
.br
.ti -1c
.RI "timeval \fBgetRTCPCheckInterval\fP (\fBRTPSessionBase\fP &s)"
.br
.ti -1c
.RI "size_t \fBtakeInDataPacket\fP (\fBRTPSessionBase\fP &s)"
.br
.ti -1c
.RI "size_t \fBdispatchDataPacket\fP (\fBRTPSessionBase\fP &s)"
.br
.ti -1c
.RI "void \fBcontrolReceptionService\fP (\fBRTPSessionBase\fP &s)"
.br
.ti -1c
.RI "void \fBcontrolTransmissionService\fP (\fBRTPSessionBase\fP &s)"
.br
.ti -1c
.RI "SOCKET \fBgetDataRecvSocket\fP (\fBRTPSessionBase\fP &s) const "
.br
.ti -1c
.RI "SOCKET \fBgetControlRecvSocket\fP (\fBRTPSessionBase\fP &s) const "
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void RTPSessionBaseHandler::controlReceptionService (\fBRTPSessionBase\fP & s)\fC [inline]\fP"
.SS "void RTPSessionBaseHandler::controlTransmissionService (\fBRTPSessionBase\fP & s)\fC [inline]\fP"
.SS "size_t RTPSessionBaseHandler::dispatchDataPacket (\fBRTPSessionBase\fP & s)\fC [inline]\fP"
.SS "SOCKET RTPSessionBaseHandler::getControlRecvSocket (\fBRTPSessionBase\fP & s) const\fC [inline]\fP"
.SS "SOCKET RTPSessionBaseHandler::getDataRecvSocket (\fBRTPSessionBase\fP & s) const\fC [inline]\fP"
.SS "timeval RTPSessionBaseHandler::getRTCPCheckInterval (\fBRTPSessionBase\fP & s)\fC [inline]\fP"
.SS "\fBmicrotimeout_t\fP RTPSessionBaseHandler::getSchedulingTimeout (\fBRTPSessionBase\fP & s)\fC [inline]\fP"
.SS "size_t RTPSessionBaseHandler::takeInDataPacket (\fBRTPSessionBase\fP & s)\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for ccRTP from the source code.
