.TH "SyncSourceHandler" 3 "21 Sep 2010" "ccRTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SyncSourceHandler \- 
.PP
\fBSyncSource\fP objects modification methods.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <iqueue.h>\fP
.PP
Inherited by \fBMembershipBookkeeping\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void * \fBgetLink\fP (const \fBSyncSource\fP &source) const "
.br
.RI "\fIThis requires \fBSyncSource\fP - \fBSyncSourceHandler\fP friendship. \fP"
.ti -1c
.RI "void \fBsetLink\fP (\fBSyncSource\fP &source, void *link)"
.br
.ti -1c
.RI "void \fBsetParticipant\fP (\fBSyncSource\fP &source, \fBParticipant\fP &p)"
.br
.ti -1c
.RI "void \fBsetState\fP (\fBSyncSource\fP &source, \fBSyncSource::State\fP ns)"
.br
.ti -1c
.RI "void \fBsetSender\fP (\fBSyncSource\fP &source, bool active)"
.br
.ti -1c
.RI "void \fBsetDataTransportPort\fP (\fBSyncSource\fP &source, tpport_t p)"
.br
.ti -1c
.RI "void \fBsetControlTransportPort\fP (\fBSyncSource\fP &source, tpport_t p)"
.br
.ti -1c
.RI "void \fBsetNetworkAddress\fP (\fBSyncSource\fP &source, InetAddress addr)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBSyncSourceHandler\fP ()"
.br
.ti -1c
.RI "virtual \fB~SyncSourceHandler\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBSyncSource\fP objects modification methods. 

\fBAuthor:\fP
.RS 4
Federico Montesino Pouzols <fedemp@altern.org> 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "SyncSourceHandler::SyncSourceHandler ()\fC [inline, protected]\fP"
.SS "virtual SyncSourceHandler::~SyncSourceHandler ()\fC [inline, protected, virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "void* SyncSourceHandler::getLink (const \fBSyncSource\fP & source) const\fC [inline]\fP"
.PP
This requires \fBSyncSource\fP - \fBSyncSourceHandler\fP friendship. Get the SyncSourceLink corresponding to a \fBSyncSource\fP object. 
.PP
Reimplemented in \fBMembershipBookkeeping\fP.
.SS "void SyncSourceHandler::setControlTransportPort (\fBSyncSource\fP & source, tpport_t p)\fC [inline]\fP"
.SS "void SyncSourceHandler::setDataTransportPort (\fBSyncSource\fP & source, tpport_t p)\fC [inline]\fP"
.SS "void SyncSourceHandler::setLink (\fBSyncSource\fP & source, void * link)\fC [inline]\fP"
.SS "void SyncSourceHandler::setNetworkAddress (\fBSyncSource\fP & source, InetAddress addr)\fC [inline]\fP"
.SS "void SyncSourceHandler::setParticipant (\fBSyncSource\fP & source, \fBParticipant\fP & p)\fC [inline]\fP"
.SS "void SyncSourceHandler::setSender (\fBSyncSource\fP & source, bool active)\fC [inline]\fP"
.SS "void SyncSourceHandler::setState (\fBSyncSource\fP & source, \fBSyncSource::State\fP ns)\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for ccRTP from the source code.
