.TH "CryptoContext.h" 3 "21 Sep 2010" "ccRTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CryptoContext.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cc++/config.h>\fP
.br
\fC#include <ccrtp/rtppkt.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCryptoContext\fP"
.br
.RI "\fIThe implementation for a SRTP cryptographic context. \fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBREPLAY_WINDOW_SIZE\fP   64"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBSrtpAuthenticationNull\fP = 0"
.br
.ti -1c
.RI "const int \fBSrtpAuthenticationSha1Hmac\fP = 1"
.br
.ti -1c
.RI "const int \fBSrtpEncryptionNull\fP = 0"
.br
.ti -1c
.RI "const int \fBSrtpEncryptionAESCM\fP = 1"
.br
.ti -1c
.RI "const int \fBSrtpEncryptionAESF8\fP = 2"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define REPLAY_WINDOW_SIZE   64"
.SH "Variable Documentation"
.PP 
.SS "const int \fBSrtpAuthenticationNull\fP = 0"
.SS "const int \fBSrtpAuthenticationSha1Hmac\fP = 1"
.SS "const int \fBSrtpEncryptionAESCM\fP = 1"
.SS "const int \fBSrtpEncryptionAESF8\fP = 2"
.SS "const int \fBSrtpEncryptionNull\fP = 0"
.SH "Author"
.PP 
Generated automatically by Doxygen for ccRTP from the source code.
