.TH "ParticipantHandler" 3 "21 Sep 2010" "ccRTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParticipantHandler \- 
.PP
\fBParticipant\fP objects modification methods.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <iqueue.h>\fP
.PP
Inherited by \fBMembershipBookkeeping\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetSDESItem\fP (\fBParticipant\fP *part, \fBSDESItemType\fP item, const std::string &val)"
.br
.ti -1c
.RI "void \fBsetPRIVPrefix\fP (\fBParticipant\fP *part, const std::string val)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBParticipantHandler\fP ()"
.br
.ti -1c
.RI "virtual \fB~ParticipantHandler\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBParticipant\fP objects modification methods. 

\fBAuthor:\fP
.RS 4
Federico Montesino Pouzols <fedemp@altern.org> 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "ParticipantHandler::ParticipantHandler ()\fC [inline, protected]\fP"
.SS "virtual ParticipantHandler::~ParticipantHandler ()\fC [inline, protected, virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "void ParticipantHandler::setPRIVPrefix (\fBParticipant\fP * part, const std::string val)\fC [inline]\fP"
.SS "void ParticipantHandler::setSDESItem (\fBParticipant\fP * part, \fBSDESItemType\fP item, const std::string & val)\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for ccRTP from the source code.
