.TH "RTCPCompoundHandler::SendReport" 3 "21 Sep 2010" "ccRTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTCPCompoundHandler::SendReport \- 
.PP
Struct for SR (sender report) RTCP packets.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rtcppkt.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32 \fBssrc\fP"
.br
.RI "\fIsource identifier. \fP"
.ti -1c
.RI "\fBSenderInfo\fP \fBsinfo\fP"
.br
.RI "\fIactual sender info. \fP"
.ti -1c
.RI "\fBRRBlock\fP \fBblocks\fP [1]"
.br
.RI "\fIpossibly several receiver info blocks. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Struct for SR (sender report) RTCP packets. 
.SH "Member Data Documentation"
.PP 
.SS "\fBRRBlock\fP \fBRTCPCompoundHandler::SendReport::blocks\fP[1]"
.PP
possibly several receiver info blocks. 
.SS "\fBSenderInfo\fP \fBRTCPCompoundHandler::SendReport::sinfo\fP"
.PP
actual sender info. 
.SS "uint32 \fBRTCPCompoundHandler::SendReport::ssrc\fP"
.PP
source identifier. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ccRTP from the source code.
