.TH "RTCPCompoundHandler::SDESItem" 3 "21 Sep 2010" "ccRTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTCPCompoundHandler::SDESItem \- 
.PP
Struct for an item description of a SDES packet.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rtcppkt.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8 \fBtype\fP"
.br
.RI "\fIitem identifier. \fP"
.ti -1c
.RI "uint8 \fBlen\fP"
.br
.RI "\fIitem len in octets. \fP"
.ti -1c
.RI "char \fBdata\fP [1]"
.br
.RI "\fIitem content. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Struct for an item description of a SDES packet. 
.SH "Member Data Documentation"
.PP 
.SS "char \fBRTCPCompoundHandler::SDESItem::data\fP[1]"
.PP
item content. 
.SS "uint8 \fBRTCPCompoundHandler::SDESItem::len\fP"
.PP
item len in octets. 
.SS "uint8 \fBRTCPCompoundHandler::SDESItem::type\fP"
.PP
item identifier. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ccRTP from the source code.
