.TH "RTCPCompoundHandler::BYEPacket" 3 "21 Sep 2010" "ccRTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTCPCompoundHandler::BYEPacket \- 
.PP
Struct for BYE (leaving session) RTCP packets.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rtcppkt.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32 \fBssrc\fP"
.br
.RI "\fIssrc identifier of source leaving. \fP"
.ti -1c
.RI "uint8 \fBlength\fP"
.br
.RI "\fI[optional] length of reason. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Struct for BYE (leaving session) RTCP packets. 
.SH "Member Data Documentation"
.PP 
.SS "uint8 \fBRTCPCompoundHandler::BYEPacket::length\fP"
.PP
[optional] length of reason. 
.SS "uint32 \fBRTCPCompoundHandler::BYEPacket::ssrc\fP"
.PP
ssrc identifier of source leaving. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ccRTP from the source code.
