.TH "rtp.h" 3 "21 Sep 2010" "ccRTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rtp.h \- 
.PP
Generic and audio/video profile specific RTP interface of ccRTP.  

.SH SYNOPSIS
.br
.PP
\fC#include <ccrtp/cqueue.h>\fP
.br
\fC#include <ccrtp/channel.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTRTPSessionBase< RTPDataChannel, RTCPChannel, ServiceQueue >\fP"
.br
.ti -1c
.RI "class \fBSingleThreadRTPSession< RTPDataChannel, RTCPChannel, ServiceQueue >\fP"
.br
.RI "\fIThis template class adds the threading aspect to the \fBRTPSessionBase\fP template in one of the many possible ways. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBSingleThreadRTPSession\fP \fBRTPSession\fP"
.br
.RI "\fIUses two pairs of sockets for RTP data and RTCP transmission/reception. \fP"
.ti -1c
.RI "typedef \fBRTPSession\fP \fBRTPSocket\fP"
.br
.RI "\fIAlias for RTPSession. \fP"
.ti -1c
.RI "typedef \fBSingleThreadRTPSession\fP< \fBSymmetricRTPChannel\fP, \fBSymmetricRTPChannel\fP > \fBSymmetricRTPSession\fP"
.br
.RI "\fIUses one pair of sockets, (1) for RTP data and (2) for RTCP transmission/reception. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Generic and audio/video profile specific RTP interface of ccRTP. 

The classes and types in this header provide general RTP functionality (following RFC 3550) as well as audio/video RTP profile specific functionality (following RFC 3551). 
.SH "Author"
.PP 
Generated automatically by Doxygen for ccRTP from the source code.
