.TH "rtppkt.h" 3 "21 Sep 2010" "ccRTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rtppkt.h \- 
.PP
RTP packets handling.  

.SH SYNOPSIS
.br
.PP
\fC#include <ccrtp/base.h>\fP
.br
\fC#include <ccrtp/formats.h>\fP
.br
\fC#include <ccrtp/CryptoContext.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRTPPacket\fP"
.br
.RI "\fIA base class for both \fBIncomingRTPPkt\fP and \fBOutgoingRTPPkt\fP. \fP"
.ti -1c
.RI "struct \fBRTPPacket::RTPFixedHeader\fP"
.br
.RI "\fIRTP fixed header as it is send through the network. \fP"
.ti -1c
.RI "struct \fBRTPPacket::RFC2833Payload\fP"
.br
.RI "\fIa structure defining RFC2833 Telephony events. \fP"
.ti -1c
.RI "struct \fBRTPPacket::RTPHeaderExt\fP"
.br
.RI "\fIFixed component of the variable-length header extension, appended to the fixed header, after the CSRC list, when X == 1. \fP"
.ti -1c
.RI "class \fBOutgoingRTPPkt\fP"
.br
.RI "\fIRTP packets being sent. \fP"
.ti -1c
.RI "class \fBIncomingRTPPkt\fP"
.br
.RI "\fIRTP packets received from other participants. \fP"
.in -1c
.SH "Detailed Description"
.PP 
RTP packets handling. 


.SH "Author"
.PP 
Generated automatically by Doxygen for ccRTP from the source code.
