.TH "RTPSessionBase" 3 "21 Sep 2010" "ccRTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTPSessionBase \- 
.PP
Generic RTP protocol stack for exchange of realtime data.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rtp.h>\fP
.SH "Detailed Description"
.PP 
Generic RTP protocol stack for exchange of realtime data. 

This stack uses the concept of packet send and receive queues to schedule and buffer outgoing packets and to arrange or reorder incoming packets as they arrive.
.PP
This is a template class that allows customization of two aspects: the underlying network and the control protocol. The RTPDataChannel and RTCPChannel template parameters specify the socket types to use. The ServiceQueue template parameter specify which packet queue is used.
.PP
\fBRTPSessionBase\fP objects do not have any threading policy, thus allowing to customize this aspect in derived classes (see \fBSingleThreadRTPSession\fP or RTPSessionPoolBase).
.PP
\fBAuthor:\fP
.RS 4
David Sugar <dyfet@ostel.com> RTP protocol stack based on Common C++. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for ccRTP from the source code.
