.TH "SingleRTPSessionPool" 3 "21 Sep 2010" "ccRTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SingleRTPSessionPool \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pool.h>\fP
.PP
Inherits \fBRTPSessionPool\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSingleRTPSessionPool\fP (int pri=0)"
.br
.ti -1c
.RI "\fB~SingleRTPSessionPool\fP ()"
.br
.ti -1c
.RI "void \fBstartRunning\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBrun\fP ()"
.br
.RI "\fIRunnable method for the thread. \fP"
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SingleRTPSessionPool::SingleRTPSessionPool (int pri = \fC0\fP)\fC [inline]\fP"\fBParameters:\fP
.RS 4
\fIpri\fP optional thread priority value. 
.RE
.PP

.SS "SingleRTPSessionPool::~SingleRTPSessionPool ()\fC [inline]\fP"
.SH "Member Function Documentation"
.PP 
.SS "void SingleRTPSessionPool::run ()\fC [protected]\fP"
.PP
Runnable method for the thread. This thread serves all the RTP sessions.added to this pool. 
.SS "void SingleRTPSessionPool::startRunning ()\fC [inline, virtual]\fP"
.PP
Implements \fBRTPSessionPool\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for ccRTP from the source code.
