.TH "DualRTPChannel" 3 "21 Sep 2010" "ccRTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DualRTPChannel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <channel.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDualRTPChannel\fP (const InetAddress &ia, tpport_t port)"
.br
.ti -1c
.RI "\fB~DualRTPChannel\fP ()"
.br
.ti -1c
.RI "bool \fBisPendingRecv\fP (\fBmicrotimeout_t\fP timeout) const "
.br
.ti -1c
.RI "InetHostAddress \fBgetSender\fP (tpport_t &port) const "
.br
.ti -1c
.RI "size_t \fBrecv\fP (unsigned char *buffer, size_t len)"
.br
.ti -1c
.RI "size_t \fBgetNextPacketSize\fP () const "
.br
.ti -1c
.RI "Socket::Error \fBsetMulticast\fP (bool enable)"
.br
.ti -1c
.RI "Socket::Error \fBjoin\fP (const InetMcastAddress &ia, uint32 iface)"
.br
.ti -1c
.RI "Socket::Error \fBdrop\fP (const InetMcastAddress &ia)"
.br
.ti -1c
.RI "Socket::Error \fBsetTimeToLive\fP (unsigned char ttl)"
.br
.ti -1c
.RI "void \fBsetPeer\fP (const InetAddress &host, tpport_t port)"
.br
.ti -1c
.RI "size_t \fBsend\fP (const unsigned char *const buffer, size_t len)"
.br
.ti -1c
.RI "SOCKET \fBgetRecvSocket\fP () const "
.br
.ti -1c
.RI "void \fBendSocket\fP ()"
.br
.in -1c

.SS "template<class BaseSocket> class DualRTPChannel< BaseSocket >"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class BaseSocket > \fBDualRTPChannel\fP< BaseSocket >::\fBDualRTPChannel\fP (const InetAddress & ia, tpport_t port)\fC [inline]\fP"
.SS "template<class BaseSocket > \fBDualRTPChannel\fP< BaseSocket >::~\fBDualRTPChannel\fP ()\fC [inline]\fP"
.SH "Member Function Documentation"
.PP 
.SS "template<class BaseSocket > Socket::Error \fBDualRTPChannel\fP< BaseSocket >::drop (const InetMcastAddress & ia)\fC [inline]\fP"
.SS "template<class BaseSocket > void \fBDualRTPChannel\fP< BaseSocket >::endSocket ()\fC [inline]\fP"
.SS "template<class BaseSocket > size_t \fBDualRTPChannel\fP< BaseSocket >::getNextPacketSize () const\fC [inline]\fP"
.SS "template<class BaseSocket > SOCKET \fBDualRTPChannel\fP< BaseSocket >::getRecvSocket () const\fC [inline]\fP"
.SS "template<class BaseSocket > InetHostAddress \fBDualRTPChannel\fP< BaseSocket >::getSender (tpport_t & port) const\fC [inline]\fP"
.SS "template<class BaseSocket > bool \fBDualRTPChannel\fP< BaseSocket >::isPendingRecv (\fBmicrotimeout_t\fP timeout) const\fC [inline]\fP"
.SS "template<class BaseSocket > Socket::Error \fBDualRTPChannel\fP< BaseSocket >::join (const InetMcastAddress & ia, uint32 iface)\fC [inline]\fP"
.SS "template<class BaseSocket > size_t \fBDualRTPChannel\fP< BaseSocket >::recv (unsigned char * buffer, size_t len)\fC [inline]\fP"
.SS "template<class BaseSocket > size_t \fBDualRTPChannel\fP< BaseSocket >::send (const unsigned char *const  buffer, size_t len)\fC [inline]\fP"
.SS "template<class BaseSocket > Socket::Error \fBDualRTPChannel\fP< BaseSocket >::setMulticast (bool enable)\fC [inline]\fP"
.SS "template<class BaseSocket > void \fBDualRTPChannel\fP< BaseSocket >::setPeer (const InetAddress & host, tpport_t port)\fC [inline]\fP"
.SS "template<class BaseSocket > Socket::Error \fBDualRTPChannel\fP< BaseSocket >::setTimeToLive (unsigned char ttl)\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for ccRTP from the source code.
