.TH "ioqueue.h" 3 "21 Sep 2010" "ccRTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ioqueue.h \- 
.PP
Generic RTP input/output queues.  

.SH SYNOPSIS
.br
.PP
\fC#include <ccrtp/iqueue.h>\fP
.br
\fC#include <ccrtp/oqueue.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRTPDataQueue\fP"
.br
.RI "\fIA packet queue handler for building different kinds of RTP protocol systems. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Generic RTP input/output queues. 


.SH "Author"
.PP 
Generated automatically by Doxygen for ccRTP from the source code.
