INCLUDEPATH += /home/saswat/workspacep/twinkll/twinklesrpp/src
INCLUDEPATH +=
INCLUDEPATH +=  
INCLUDEPATH += /usr/include/libxml2  
LIBS +=
LIBS += -L/usr/lib -lccext2 -lccgnu2 -lz -ldl -lrt -pthread
LIBS += -pthread -lccrtp1 -lccgnu2 -ldl -lrt  
LIBS += -lxml2  
LIBS += -lresolv
LIBS += ../audio/gsm/libgsm.a
LIBS += -lasound
LIBS += -lspeex
LIBS += -lspeexdsp
LIBS += -lboost_regex
